### ISSUE TITLE
AutoIT control_click not working

### ISSUE THREAD

**Issue by shauryauppal** [jacexh/pyautoit#25]
Traceback (most recent call last):
  File "rough.py", line 7, in <module>
    autoit.control_click("[Class:Notepad]", "Button2")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\autoit\autoit.py", line 84, in wrapper
    raise AutoItError(err_msg)
autoit.autoit.AutoItError: send click message failed

**Comment by shauryauppal** [comment]
It works after installation of PyWhatsapp from repo 'python setup.py install'
