### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by DarthOpto** [jacexh/pyautoit#4]
I am trying to install this on a Windows 8.1 64 bit system. I have AutoIT installed and have registered the AutoItX3 dll files for both the 32 bit and 64 bit dlls. When I try the python setup.py install or the pip installation method, I am getting the following error:

[Error 193] %1 is not a valid Win32 Application
![pyautoit error](https://cloud.githubusercontent.com/assets/7504395/6332340/e9d2b848-bb41-11e4-8722-a74d3f0eda86.png)

**Comment by jacexh** [comment]
hi, which version of python do you installed?

**Comment by DarthOpto** [comment]
I have 2.7.9 installed

Curtis Salisbury, MBA, MHRM
curtis.salisbury@gmail.com
curtissalisbury@yahoo.com

(801)310-4173 (Mobile)
(801)899-2143 (Home)

**Comment by DarthOpto** [comment]
64 bit version

Curtis Salisbury, MBA, MHRM
curtis.salisbury@gmail.com
curtissalisbury@yahoo.com

(801)310-4173 (Mobile)
(801)899-2143 (Home)

**Comment by DarthOpto** [comment]
When I attempt to install to a Linux or OSx environment, I am getting the following error:

Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pyautoit/setup.py", line 9, in <module>
        import autoit
      File "autoit/__init__.py", line 6, in <module>
        from .autoit import options, properties, commands
      File "autoit/autoit.py", line 7, in <module>
        from ctypes.wintypes import *
      File "/usr/lib/python2.7/ctypes/wintypes.py", line 23, in <module>
        class VARIANT_BOOL(_SimpleCData):
    ValueError: _type_ 'v' not supported
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pyautoit/setup.py", line 9, in <module>

    import autoit

  File "autoit/__init__.py", line 6, in <module>

    from .autoit import options, properties, commands

  File "autoit/autoit.py", line 7, in <module>

    from ctypes.wintypes import *

  File "/usr/lib/python2.7/ctypes/wintypes.py", line 23, in <module>

    class VARIANT_BOOL(_SimpleCData):

ValueError: _type_ 'v' not supported

**Comment by jacexh** [comment]
Please try 32 bit version of python.
autoItx.dll only support for windows, it cannot be installed into Linux/Unix.

**Comment by jkyeung** [comment]
You included both 32-bit and 64-bit versions of the AutoIt DLL, but your test of whether to use the 64-bit version (near the top of `autoit.py`) is wrong. The `PROGRAMFILES` environment variable is always `C:\Program Files`, no matter the bitness of Windows. I don't think it's important to check the bitness of Windows anyway, because you shouldn't ever have a 64-bit Python on a 32-bit Windows. Therefore, once you have determined that you have a 64-bit Python, you might as well just go ahead and use the 64-bit DLL.

The following lines in `autoit.py`:

    if "(x86)" in os.environ['PROGRAMFILES'] and bit == "64bit":
        # if 64bit version of python within 64bit version of Windows,
        # load AutoItX3_x64.dll
        dll = "AutoItX3_x64.dll"

should be

    if bit == "64bit":
        # if 64bit version of python, load AutoItX3_x64.dll
        dll = "AutoItX3_x64.dll"

That will at least get the package to import properly. When I tried the simple script in the PyAutoIt README on my 64-bit Python 2.7, the `control_click()` failed, but that's a separate issue.

**Comment by jacexh** [comment]
I merged this patch, thank you for your feedback.

**Comment by kotofos** [comment]
Can you please also update pypi package?

**Comment by jacexh** [comment]
@kotofos try this: `pip install -U https://github.com/jacexh/pyautoit/archive/master.zip`

**Comment by sahan80** [comment]
hi, I have used pip install -U https://github.com/jacexh/pyautoit/archive/master.zip it installed successfully. But when I am trying to import pyautoit in IDLE it throwing an exception like 

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pyautoit
ImportError: No module named 'pyautoit'

please help...

**Comment by jacexh** [comment]
@sahan80 the package name is `autoit`

**Comment by sahan80** [comment]
oh sorry for that, it is working fine now with autoit

**Comment by dsenkyrova** [comment]
Hi guys I am trying to install on linux but I get the following error
------------------------------------------------------------
/usr/bin/pip run on Tue May 30 06:26:28 2017
Downloading/unpacking pyautoit
  Getting page https://pypi.python.org/simple/pyautoit/
  URLs to search for versions for pyautoit:
  * https://pypi.python.org/simple/pyautoit/
  Analyzing links from page https://pypi.python.org/simple/pyautoit/
    Found link https://pypi.python.org/packages/0d/5f/3a31a33b9ef207bd46c88d52812dff2e2dca136bc1c59dc0378f011cc4d9/PyAutoIt-0.1.zip#md5=c6efc5e9756dcabef4fbba5e7f40bcb5 (from https://pypi.python.org/simple/pyautoit/), version: 0.1
    Found link https://pypi.python.org/packages/21/19/561e8371404d77f7b0ec34d4c45e2d99f8eb48f5bbb7c88d222773dfdd70/PyAutoIt-0.4.zip#md5=621aeaa70a3ab6ef28a2b40fc7acbf25 (from https://pypi.python.org/simple/pyautoit/), version: 0.4
    Found link https://pypi.python.org/packages/35/36/bcc35c5d1d4efd3313967553ba3ba6fba14d90c26a90b037e8258b72d452/PyAutoIt-0.3.zip#md5=4a2b753e023bc320f94a0c97e46a1310 (from https://pypi.python.org/simple/pyautoit/), version: 0.3
    Found link https://pypi.python.org/packages/50/fe/a260ec81c9d34d6b6f72f9949175077f752b0bb8a9879bf5ecf39d69545c/PyAutoIt-0.2.zip#md5=84296e8ba34731aede3e8e03ec4ef236 (from https://pypi.python.org/simple/pyautoit/), version: 0.2
    Skipping link https://pypi.python.org/packages/8b/37/7294d79e1e6a192ee89df4f73c3693c7644d6c89b14550072353126afd32/PyAutoIt-0.3-py2.7.egg#md5=5e9ac106614fdca66cf8d26424ad3cc1 (from https://pypi.python.org/simple/pyautoit/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/bb/88/65b5452e99bf431164199730602bdf538a8551803c63af1d8a15df558746/PyAutoIt-0.2.1.zip#md5=46c17ad1242dd3e5a3f38091229f941c (from https://pypi.python.org/simple/pyautoit/), version: 0.2.1
    Found link https://pypi.python.org/packages/d9/5e/8dc5ec10065a1af3a484279296138839f8b8c1eca76c13cfde431b638595/PyAutoIt-0.2.2.zip#md5=c40d5cc50941cb766dc02d5b22d893db (from https://pypi.python.org/simple/pyautoit/), version: 0.2.2
  Using version 0.4 (newest of versions: 0.4, 0.3, 0.2.2, 0.2.1, 0.2, 0.1)
  Downloading from URL https://pypi.python.org/packages/21/19/561e8371404d77f7b0ec34d4c45e2d99f8eb48f5bbb7c88d222773dfdd70/PyAutoIt-0.4.zip#md5=621aeaa70a3ab6ef28a2b40fc7acbf25 (from https://pypi.python.org/simple/pyautoit/)
  Running setup.py (path:/tmp/pip-build-fa7FzT/pyautoit/setup.py) egg_info for package pyautoit
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-fa7FzT/pyautoit/setup.py", line 9, in <module>
        import autoit
      File "autoit/__init__.py", line 6, in <module>
        from .autoit import options, properties, commands
      File "autoit/autoit.py", line 7, in <module>
        from ctypes.wintypes import *
      File "/usr/lib64/python2.7/ctypes/wintypes.py", line 23, in <module>
        class VARIANT_BOOL(_SimpleCData):
    ValueError: _type_ 'v' not supported
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-fa7FzT/pyautoit/setup.py", line 9, in <module>

    import autoit

  File "autoit/__init__.py", line 6, in <module>

    from .autoit import options, properties, commands

  File "autoit/autoit.py", line 7, in <module>

    from ctypes.wintypes import *

  File "/usr/lib64/python2.7/ctypes/wintypes.py", line 23, in <module>

    class VARIANT_BOOL(_SimpleCData):

ValueError: _type_ 'v' not supported

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-fa7FzT/pyautoit
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 298, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1234, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/site-packages/pip/util.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-fa7FzT/pyautoit

**Comment by dmwyatt** [comment]
@dsenkyrova AutoIT is Windows-only, so this library will not work on Linux.

**Comment by balup34** [comment]
+1

**Comment by Vinodkumar545** [comment]
Hi,

what is the alternative package/tool for linux? Clearly, pyautoit only works for windows. What about linux user??

Could you please provide some suggestions here.

Vinod

**Comment by stuaxo** [comment]
Hi,
   Just another confirmation that installing from git with pip works, any chance of this making it into a release and onto pypi?

S

**Comment by kyc1109** [comment]
I also have the same problem in win10 64bit.
I remove AutoItX3.dll (win32) and then rename from AutoItX3_x64.dll (64 version) to AutoItX3.dll. then re-install again, is work. But not sure have any risk.
