### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by maulerbone** [jacexh/pyautoit#5]
C:\Downloads\python\pyautoit-master\pyautoit-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import autoit
  File "C:\Downloads\python\pyautoit-master\pyautoit-master\autoit__init__.py", line 6, in <module>
    from .autoit import options, properties, commands
  File "C:\Downloads\python\pyautoit-master\pyautoit-master\autoit\autoit.py", line 28, in <module>
    AUTO_IT = ctypes.windll.LoadLibrary(dll_path)
  File "C:\Python27\lib\ctypes__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

C:\Downloads\python\pyautoit-master\pyautoit-master>python
Python 2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by jacexh** [comment]
take a look at https://github.com/jacexh/pyautoit/issues/4
